version: '3.8'

services:
  english-bot:
    build: .
    container_name: english-bot
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - bot-network
    volumes:
      - ./logs:/app/logs
      - ./temp:/app/temp

  postgres:
    image: postgres:14
    container_name: english-bot-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_DB=english
      - POSTGRES_USER=assistent
      - POSTGRES_PASSWORD=password123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bot-network
    ports:
      - "5435:5432"  # Используем порт 5434 чтобы не конфликтовать с другими проектами

volumes:
  postgres_data:

networks:
  bot-network:
    driver: bridge
